auto_aim:
  armor_detector:
    debug: true
    binary_thres: 140
    detect_color: RED
    lights_params:
      min_ratio: 0.1
      max_ratio: 0.5
      max_angle: 35.0
      min_fill_ratio : 0.8
      color_diff_thresh : 20.0
    armors_params:
      min_light_ratio: 0.7
      min_small_center_distance: 0.8
      max_small_center_distance: 3.2
      min_large_center_distance: 3.2
      max_large_center_distance: 5.5
      max_angle: 35.0
    number_params:
      model_path: ../auto_aim/armor_detector/model/lenet.onnx
      label_path: ../auto_aim/armor_detector/model/label.txt
      classifier_threshold: 0.7
      ignore_classes: ["negative"]