auto_aim:
  armor_detector:
    debug: true
    binary_thres: 140
    detect_color: RED
    lights_params:
      min_ratio: 0.01
      max_ratio: 1.0
      max_angle: 45.0
      min_fill_ratio : 0.6
      color_diff_thresh : 20.0
    armors_params:
      min_light_ratio: 0.7
      min_small_center_distance: 0.8
      max_small_center_distance: 3.5
      min_large_center_distance: 3.5
      max_large_center_distance: 8.0
      max_angle: 35.0
    number_params:
      model_path: ../auto_aim/armor_detector/model/lenet.onnx
      label_path: ../auto_aim/armor_detector/model/label.txt
      classifier_threshold: 0.7
      ignore_classes: ["negative"]
  tracker:
    min_detect_count: 5
    max_temp_lost_count: 10
    outpost_max_temp_lost_count: 30