camera:
  exposuretime: 4000.0
  gain: 10.0
calibration:
  board_width: 7
  board_height: 10
  square_size: 0.0235
  min_images: 10
  max_images: 250
  output_file: "config/camera_calibration.json"
display: true
record:
  enabled: false
  fps: 30.0
# 添加模式配置：camera 或 video
mode: "video"
# 视频配置（仅在mode为video时使用）
video:
  path: "test.mp4"
  fps: 30.0